apiVersion: apps/v1
kind: Deployment
metadata:
  name: pan-ocr
  namespace: dev-divs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pan-ocr
  template:
    metadata:
      labels:
        app: pan-ocr
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: pancard-ocr
          image: 427157662616.dkr.ecr.ap-south-1.amazonaws.com/pancard-ocr-svc:v1.1.1
          workingDir: /app       # set working directory
          ports:
            - containerPort: 8000
          command: ["uvicorn"]
          args: ["api.server:app", "--host", "0.0.0.0", "--port", "8000"]
          volumeMounts:
            - name: pan-ocr-config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: pan-ocr-config
          configMap:
            name: pan-ocr-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-ocr-config
  namespace: dev-divs
data:
  config.yaml: |
    kafka:
      brokers: vectordb-kafka-headless.dev-divs:9093
      consumer_group: "divs-pan-ocr-validation"
      topic_in: "divs_pan"
      topic_out: "divs_verifier"
    aws:
      bucket_name: speedpay.india
      prefix: divs/images
    ocr:
      model_path: /models/pan-ocr
---
apiVersion: v1
kind: Service
metadata:
  name: pan-ocr-svc
  namespace: dev-divs
spec:
  selector:
    app: pan-ocr
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
