apiVersion: v1
kind: Service
metadata:
  name: pan-ocr-service
  namespace: dev-divs
spec:
  selector:
    app: pan-ocr
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8087 
